package main

import (
	"math/rand"
	"strings"
)

func getFill(category string) string {
	// only take last 3
	token := strings.ToLower(category)
	if len(token) > 3 {
		token = token[len(token)-3:]
	}
	cat := fillDialogue[token]
	if len(cat) == 0 {
		return "uh"
	}
	return cat[rand.Intn(len(cat))]
}

var fillDialogue = map[string][]string{
	"atk": {
		"For glory!", "Your blood will stain the earth!", "I'll cut you down!", "Feel my blade!",
		"Die, intruder!", "To arms!", "You dare face me?", "I'll end you here!",
		"No mercy!", "You picked the wrong fight!", "I'll crush you!", "Have at you!",
		"This is your end!", "Taste steel!", "Fall before me!", "I'll gut you!",
		"You will not leave alive!", "Prepare to die!", "Feel my wrath!", "I'll tear you apart!",
		"Die screaming!", "I'll make you suffer!", "I'll split you in two!", "You'll regret this!",
		"Attack!", "Kill them all!", "Blood for blood!", "You won't survive!",
		"Stand and fight!", "Your bones will break!", "Your head is mine!", "Time to die!",
		"You face death!", "This one's mine!", "Cut them down!", "I'll burn you!",
		"I'll smash you!", "No escape!", "You won't leave alive!", "You are doomed!",
		"I'll feed you to the crows!", "Feel my steel!", "I'll have your head!", "Fight me!",
		"Blood and steel!", "You'll fall today!", "Face your death!", "This is my fury!",
		"By my blade!", "Fall, wretch!", "You'll pay in blood!", "None can withstand me!",
		"I'll carve you up!", "Die quickly!", "Time to bleed!", "I'll rip you apart!",
		"You'll beg for mercy!", "Death is upon you!", "I'll skewer you!", "I'll break you!",
		"Your life ends here!", "I'll spill your guts!", "I'll crush your skull!", "Fall before my strength!",
		"This is the end!", "You won't win!", "For honor!", "Die by my hand!",
		"I'll drown you in blood!", "Your doom is here!", "Feel death's embrace!", "Your soul is mine!",
		"I'll cleave you in two!", "You're finished!", "Perish!", "Fall like the rest!",
		"You cannot escape!", "I'll hunt you down!", "Die like a dog!", "You've sealed your fate!",
		"I'll leave nothing!", "Your fate is sealed!", "Now you die!", "Fall, cur!",
		"I'll show no mercy!", "You'll be ashes!", "Time to kill!", "By steel and fire!",
		"I'll destroy you!", "I'll crush your spirit!", "No one will mourn you!", "You'll die here!",
		"Your time is done!", "Death takes you!", "You'll fall beneath me!", "You'll be dust!",
		"This fight is mine!", "I'll strike you down!", "Die by my steel!", "Fall to ruin!",
	},
	"fle": {
		"No, I must live to fight another day!", "Stay back!", "Help me!", "I can't win this!",
		"Run away!", "Spare me!", "Don't kill me!", "I yield!", "Mercy!", "Leave me be!",
		"I'll flee!", "No more!", "Save me!", "I can't go on!", "I'm beaten!", "Don't hurt me!",
		"Let me live!", "I surrender!", "Stay away!", "No more fighting!", "I'm done!", "I quit!",
		"Forgive me!", "I can't fight this!", "I'm overmatched!", "I must retreat!", "I'll come back stronger!",
		"You win!", "You've bested me!", "Stop this!", "Don't chase me!", "I'm outmatched!",
		"Spare my life!", "I can't take more!", "I'll not die here!", "Please no!", "I can't win!",
		"No! No!", "Help, anyone!", "Not like this!", "I'll be back!", "Too strong!",
		"I won't die here!", "Stay away from me!", "I must go!", "I need help!",
		"I can't stand it!", "No more blood!", "Please, I beg you!", "Stop chasing me!",
		"Run for your lives!", "I can't fight anymore!", "I yield to you!", "No more pain!",
		"Don't hurt me again!", "Stay your blade!", "This isn't worth my life!", "Let me go!",
		"I must get away!", "I'm not ready to die!", "No, stop!", "Mercy, please!",
		"Not today!", "I'll escape!", "I can't handle this!", "I need to flee!",
		"Don't make me die here!", "No! Spare me!", "I'll run!", "This isn't my fight!",
		"Let me run!", "I'm scared!", "I don't want to die!", "I need to leave!",
		"I'm too weak!", "I've lost!", "I'm leaving!", "Let me be!",
		"Don't follow me!", "I'm going!", "Don't do this!", "Why me?",
		"Stop, please!", "I've had enough!", "Let me live!", "I'll come back!",
		"Not worth dying for!", "This is too much!", "I give up!", "You're too strong!",
		"I'll retreat now!", "I'll find safety!", "Not now!", "Another day!",
		"I'll survive!", "You win this time!", "I'll go now!", "Don't end me here!",
	},
	"idl": {
		"The weather's been strange of late.", "I wonder what's for supper tonight.",
		"Have you heard the news from the capital?", "The roads are dangerous these days.",
		"Another storm is brewing.", "I hope the harvest is good this year.",
		"The inn's ale is weaker than before.", "Game is scarce in the woods.",
		"I saw a strange light in the sky.", "The price of grain is too high.",
		"Merchants bring odd goods from far lands.", "The children play too close to the well.",
		"I heard wolves howling last night.", "Travelers tell of war in the east.",
		"This town is quiet… too quiet.", "We'll need more firewood soon.",
		"The river runs faster this year.", "I saw tracks by the old mill.",
		"The night feels colder than usual.", "Some say ghosts walk the marshes.",
		"I don't trust the new smith.", "They say the king is ill.",
		"I wonder what tomorrow brings.", "The well water tastes strange.",
		"Bandits roam these parts.", "The tavern keeps busy these nights.",
		"I saw a caravan arrive this morning.", "The moon looked red last night.",
		"A storm ruined the crops last year.", "Some say dragons once lived here.",
		"Folk whisper of curses in the forest.", "The road south is washed out.",
		"Hunters say the deer are lean this year.", "The mayor seems troubled.",
		"Children went missing long ago.", "This land has many stories.",
		"I saw a shooting star yesterday.", "My boots are worn through.",
		"I heard singing in the night.", "The old ruins still stand.",
		"Merchants were robbed nearby.", "We need more guards in town.",
		"The old priest is wise.", "The baker's bread is the best.",
		"Do you think it will rain?", "The well runs low.", "Our sheep stray too often.",
		"I saw a fox near the chickens.", "The candles burn fast.", "Strange noises at night.",
		"The forest is dark and deep.", "We need stronger walls.", "Our fields grow weeds.",
		"The well freezes in winter.", "I saw strangers pass by.", "The smith hammers late.",
		"The river floods each spring.", "There are whispers in the tavern.",
		"Fishermen say the lake is empty.", "A child was born last night.",
		"A hunter brought in a great stag.", "We need a healer soon.",
		"The roads are muddy.", "I lost a shoe in the muck.",
		"The cobbler's work is fine.", "We need more candles.", "I saw shadows move.",
		"The stars shine bright.", "I heard of a wedding.", "A baby cried last night.",
		"I lost my coin purse.", "The guards march often.", "We need more wood.",
		"I found an old coin.", "The tavern was loud.", "The road is long.",
		"I saw a hawk flying.", "The dogs barked at dawn.", "The sun feels hot.",
		"We must plant early.", "I saw smoke rising.", "Our roof leaks again.",
		"The bells rang thrice.", "The barn needs mending.", "The chickens wander.",
		"The cows need milking.", "I saw frost on the grass.", "The wind howls tonight.",
		"I dropped my spoon.", "The stew burned.", "The fence broke.",
		"We need more nails.", "I saw an owl.", "The sheep are restless.",
		"I hope for peace.", "The wheat grows tall.", "The goats escaped.",
		"I saw a rainbow.", "The rain was heavy.", "The stream runs dry.",
	},
	"flw": {
		"I'll guard your back.", "Where you go, I follow.", "I'm right behind you.", "Lead the way.",
		"I'll not leave your side.", "I go where you go.", "You can count on me.", "I'll watch over you.",
		"I'll keep close.", "I'll be your shadow.", "I'll follow without question.", "I'm with you.",
		"No path too dark if you lead.", "Your road is mine.", "I'll keep up.", "Step by step, I'm with you.",
		"You lead, I'll follow.", "I'll stand with you.", "Your fight is my fight.", "Where you tread, I tread.",
		"Your command is mine.", "I'll keep pace.", "I'll stay near.", "Your word is my bond.",
		"I'll walk beside you.", "I'm loyal to you.", "I'll protect you.", "I'll not falter.",
		"I'll stay at your side.", "I'll be your sword arm.", "I'll follow into fire.", "I'll follow into battle.",
		"I'll not stray.", "I'll be there always.", "I'll not fail you.", "Your burden is mine.",
		"I'll go where needed.", "Your journey is mine.", "Your cause is just.", "I'll not abandon you.",
		"Your fight is my duty.", "I'll watch your steps.", "Your back is safe.", "You'll never walk alone.",
		"Your enemies are mine.", "I'll match your pace.", "Your road is mine to share.", "I'll follow to the end.",
		"I'll follow through darkness.", "I'll follow through light.", "I'll stand guard for you.", "Your safety is mine.",
		"I'll not waver.", "I'll stay the course.", "I'll keep you safe.", "I'll never leave.",
		"I'll walk this path too.", "I'll stand by your side.", "I'll keep near to you.", "I'll not tire.",
		"Your call is mine to answer.", "I'll follow forever.", "Your fate is tied to mine.", "I'll stand by your word.",
		"I'll keep faithful.", "I'll follow till death.", "I'll not stray from you.", "Your shadow is mine.",
		"I'll follow without fear.", "Your steps are my steps.", "I'll stand true.", "I'll not be shaken.",
		"I'll march with you.", "I'll bear arms for you.", "I'll share your fight.", "I'll share your load.",
		"I'll walk behind you.", "I'll not lag behind.", "I'll be steadfast.", "Your lead is my guide.",
		"I'll not wander off.", "I'll follow in silence.", "Your foes are my foes.", "I'll follow faithfully.",
		"I'll stay until the end.", "I'll follow into danger.", "I'll stand watch for you.", "I'll be your strength.",
		"I'll follow, rain or shine.", "Your fight is shared.", "Your will is mine.", "I'll not break.",
		"Your path is chosen, mine as well.", "I'll follow to victory.", "Your cause is my cause.", "I'll not turn away.",
	},
	"hit": {
		"Argh!", "Ugh!", "Gah!", "Ack!", "Ungh!",
		"Oof!", "Ow!", "Ahh!", "Urgh!", "Ouch!",
		"Ragh!", "Hurgh!", "Yah!", "Augh!", "Grr!",
		"Mph!", "Eh!", "Ooph!", "Igh!", "Hurk!",
	},
	"hlo": {
		"Greetings, traveler.", "Hail, friend.", "Well met.", "Hello there.",
		"Good day to you.", "Peace upon you.", "A fine day, isn't it?", "Warm welcome.",
		"Ah, a new face.", "Hello, stranger.", "Welcome.", "Good tidings.",
		"Blessings upon you.", "A good day.", "Well met, traveler.", "Hail and well met.",
		"Greetings, friend.", "How do you fare?", "Pleasure to meet you.", "Welcome, wanderer.",
		"Hello, my friend.", "Good evening.", "Good morning.", "Hail, adventurer.",
		"May your road be clear.", "A good morning to you.", "I welcome you.", "Hail!",
		"Hello again.", "It's good to see you.", "Greetings once more.", "Welcome back.",
		"Ah, you return.", "Peace be with you.", "I greet you warmly.", "May fortune smile on you.",
		"Hello, traveler.", "Welcome, guest.", "I'm glad you came.", "Hail, companion.",
		"Good to see you again.", "Well met again.", "A fair day to you.", "Greetings, comrade.",
		"Welcome, adventurer.", "Good to meet you.", "Ah, greetings.", "Blessings on your path.",
		"Hello, wanderer.", "It's an honor.", "Good to see you.", "Welcome again.",
		"Hello, muthsera.", "Hail, ally.", "Greetings, outlander.", "May the gods keep you.",
		"Hail, wayfarer.", "Welcome, stranger.", "I bid you welcome.", "A pleasure to see you.",
		"Good to see your face.", "Hail, champion.", "Greetings again.", "Welcome, my friend.",
		"Hello and well met.", "Ah, a visitor.", "Good to see you here.", "Greetings, kin.",
		"Hail, brother.", "Hail, sister.", "Welcome, noble one.", "Ah, greetings traveler.",
		"Blessings, traveler.", "Good fortune to you.", "I welcome your company.", "Well met, stranger.",
		"Hello there again.", "A fine welcome to you.", "I'm pleased to see you.", "Welcome, guest.",
		"May your travels be safe.", "Peace on your journey.", "Good health to you.", "Hail, noble one.",
		"Greetings upon you.", "Hail to you.", "A good welcome.", "Welcome, wanderer.",
		"Hello and blessings.", "Greetings, friend indeed.", "Well met, ally.", "Ah, a good meeting.",
		"Welcome, serjo.", "Good fortune upon you.", "Blessed day to you.", "Hail, companion of roads.",
	},
	"srv": {
		"What can I get for you today?", "Take your time, browse my wares.", "Looking to buy or sell?",
		"Welcome, customer.", "I've fine goods here.", "Step right up.", "Care to trade?",
		"Have a look at my stock.", "Need something special?", "Everything's for sale.",
		"I stand by my wares.", "Best prices in town.", "You won't find better.",
		"Looking for weapons or armor?", "Fresh supplies today.", "All fair prices here.",
		"Step inside, have a look.", "A fair bargain awaits.", "I've goods from far lands.",
		"Care for a look?", "My stock is yours to see.", "Buy what you need.", "Browse freely.",
		"See anything you like?", "Tell me what you need.", "My goods are honest.",
		"Coin for goods, that's fair.", "Trade with me.", "I'll give you a fair deal.",
		"Looking for potions?", "Fresh stock today.", "Need new gear?", "I've got tools aplenty.",
		"I've something for everyone.", "Don't be shy, look around.", "A fine choice awaits.",
		"What's your need?", "Tell me your desire.", "I've rare items here.", "A good deal, I swear.",
		"You won't be cheated.", "Looking for food or drink?", "Step up, traveler.",
		"You've coin, I've goods.", "I'll not cheat you.", "Fair trade for fair coin.",
		"Have a browse.", "I stand by the quality.", "You'll not regret it.", "My stock is wide.",
		"I'll cut you a deal.", "Take a look inside.", "I've wares from the south.",
		"I've wares from the north.", "Exotic goods for sale.", "All at fair prices.",
		"See my fine wares.", "My shop is open.", "I'll treat you fair.", "What's your fancy?",
		"I've a bit of everything.", "Supplies for your journey.", "You need it, I've got it.",
		"No better shop around.", "You'll find what you seek.", "Step right in.",
		"The best deals here.", "I've fresh goods daily.", "My wares are yours to see.",
		"A fair coin buys much.", "A pleasure to serve you.", "You won't be disappointed.",
		"Have a look, friend.", "Goods for all travelers.", "I'll not overcharge.",
		"Best stock you'll find.", "Honest trade here.", "You won't find finer.",
		"Welcome to my shop.", "Looking for something?", "I've got what you need.",
		"Plenty to choose from.", "Step up, browse my wares.", "A fine selection here.",
		"Everything priced fair.", "Trade with me, friend.", "Have a look around.",
		"I sell only the best.", "My shop is yours to see.", "No finer goods anywhere.",
		"I keep fair prices.", "You'll get what you pay for.", "I've rare finds today.",
		"Care to browse?", "My stock changes daily.", "I'll treat you honestly.",
		"No tricks here, just goods.", "Coin well spent here.", "Trade is always welcome.",
		"My wares are open to you.", "Best deals under the sun.",
	},
	"thf": {
		"Hey! That's mine!", "Stop, thief!", "You won't get away with that!", "Hands off!",
		"Caught you red-handed!", "Thief!", "You dare steal from me?", "Give that back!",
		"Guards! A thief!", "Put that back!", "You think I wouldn't see?", "Caught stealing!",
		"Caught in the act!", "Drop it!", "Caught you!", "I saw that!", "Stop right there!",
		"Return what you stole!", "You'll pay for that!", "How dare you!", "You can't take that!",
		"Not yours to take!", "Caught you, thief!", "Stop this at once!", "That's stealing!",
		"I won't allow this!", "You're a thief!", "Caught again!", "Hands where I can see!",
		"Thieving scum!", "That's mine!", "You won't escape!", "Put it down!",
		"Guards, to me!", "I caught you stealing!", "You'll regret that!", "Caught in my shop!",
		"Not while I'm here!", "Return it now!", "Drop the goods!", "Caught you thieving!",
		"I'll not be robbed!", "Caught in broad daylight!", "I won't stand for this!",
		"Caught stealing again!", "Give it back now!", "I see you stealing!", "Stop, thief scum!",
		"Return my property!", "Stop him!", "Stop her!", "Stop them!",
		"Caught in the act, thief!", "Not yours!", "You'll hang for that!", "How dare you steal!",
		"That belongs to me!", "Not while I watch!", "Drop it, thief!", "Guards, seize them!",
		"That's stolen!", "I caught that!", "You can't hide that!", "You can't take that from me!",
		"Not today, thief!", "You won't leave alive!", "Return the stolen goods!", "Caught red-handed!",
		"That's not yours!", "Caught again, thief!", "Hands off my wares!", "Not in my shop!",
		"You're a bold thief!", "How dare you try this!", "You thief!", "You filthy thief!",
		"Caught stealing from me!", "Caught again, eh?", "Not yours to keep!", "Give it back, thief!",
		"Stop, I say!", "Return it at once!", "I'll call the guards!", "Caught stealing goods!",
		"Thieving won't save you!", "You can't do that here!", "You'll pay dearly for this!",
		"Not while I stand!", "You've been caught!", "You thief, stop!", "Drop the stolen goods!",
		"I see you, thief!", "You won't get far!", "Return what you took!", "Caught with my goods!",
		"You can't steal from me!", "Not so fast, thief!", "Stop your thieving!",
	},
}
